Repository tofu99/GR-2.28.2020, pull requests merged in 2020-06, with the labels that each got.

#2 Formating Changes to RPG Rules
  Russian Roulete RPG system rules.md
Labels: enhancement

#12 Convert skill keywords to table
  Russian Roulete RPG system rules.md
Labels: documentation, enhancement

#15 Add table of sample skills
  Russian Roulete RPG system rules.md
Labels: documentation, enhancement

#19 Update Russian Roulete RPG system rules.md
  Russian Roulete RPG system rules.md
Labels: awaiting-merge, enhancement

#20 Minor formatting + grammar changes
  Russian Roulete RPG system rules.md
Labels: awaiting-merge, enhancement

#18 Minor change to example skills
  Russian Roulete RPG system rules.md
Labels: awaiting-merge

#23 Formatting Changes
  Russian Roulete RPG system rules.md
Labels: awaiting-merge, enhancement

#24 Update Russian Roulete RPG system rules.md
  Russian Roulete RPG system rules.md
Labels: awaiting-merge, bug, enhancement

#25 Remove confusing information about negative skill levels
  Russian Roulete RPG system rules.md
Labels: awaiting-merge, bug
